version: '3'
services:
  # postgres-order:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: microservice_db_order
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 3572
  #     POSTGRES_PORT: 5432
  #   command: [ "-p", "5432" ]
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data_order:/var/lib/postgresql/data
  #   networks:
  #     - app

  # postgres-person:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: microservice_db_person
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 3572
  #     POSTGRES_PORT: 5433 # Порт базы данных внутри контейнера
  #   command: [ "-p", "5433" ]
  #   ports:
  #     - "5433:5433"
  #   volumes:
  #     - postgres_data_person:/var/lib/postgresql/data
  #   networks:
  #     - app

  # rabbitmq:
  #   image: "rabbitmq:management"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - app

  app_order:
    build:
      context: ./app_order
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    # depends_on:
    #   - postgres-order
    #   - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app

  app_person:
    build:
      context: ./app_person
      dockerfile: ./Dockerfile
    ports:
      - "81:81"
    # depends_on:
    #   - postgres-person
    #   - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app


  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.ru
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - app

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json"
    networks:
      - app

networks:
  app:
  # name: app
volumes:
  postgres_data_order:
  postgres_data_person: